var headers = {
    "0:0": "Hayatı",
    "0:1": "Cocuklugu ve Eğitimi",
    "0:2": " İsviçre'deki eğitimi",
    "0:3": "Bern Patent ofisi",
    "0:4": "Mileva Maric ile evliliği",
    "0:5": "Akademik kariyeri",
    "0:6": "Elsa Einstein ile evliliği",
    "0:7": "Amerikan vatandaşlığı ve Princeton, New Jersey",
    "0:8": "Ölümü ve Beyninin Çalınması",
    "1:0": "Bilimsel Çalışmaları",
    "1:1": "Özel görelilik kuramı",
    "1:2": "Genel görelilik kuramı",
    "1:3": "Kütle-enerji eşitliği",
    "1:4": "Fotoelektrik etki",
    "1:5": "Brown hareketi ve istatistiksel fizik",
    "1:6": "Bose-Einstein istatistiği",
    "1:7": "Kuantum fiziği ve belirsizlik ilkesi",
    "1:8": "Kozmoloji",
    "1:9": "Birleşik alan kuramı",
    "2:0": "Görüşleri",
    "2:1": "Politik görüşleri",
    "2:2": "Dini görüşleri",
    "3:0": "Popüler kültürde Einstein",
    "4:0": "Eserleri",
    "4:1": "Kitapları",
    "4:2": "Makaleleri"
};
